id: db-pack
focus: "SQL design, migrations, Python DB-API (PEP 249)"
allowlist:
  - postgresql.org/docs
  - peps.python.org/pep-0249
patterns:
  - "Start with schema + migrations"
  - "Use transactions, parameterized queries"
references:
  - "PostgreSQL SQL Language (current)"
  - "PEP 249: Python DB-API 2.0"
