id: av-pack
focus: "ffprobe metadata, container/codecs, streaming protocols"
allowlist:
  - ffmpeg.org
  - rfc-editor.org (RTP, HLS RFC 8216)
patterns:
  - "Use ffprobe JSON for cataloging"
  - "Choose protocol by latency vs. scale (RTP/HLS/SRT)"
references:
  - "ffprobe documentation"
  - "RFC 3550 RTP"
  - "RFC 8216 HLS"
